name: StreakBot Every 5 Minutes

on:
  schedule:
    - cron: '*/5 * * * *'  # Every 5 minutes
  workflow_dispatch:       # Manual trigger

jobs:
  streak:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Configure Git
        run: |
          git config --global user.name "StreakBot"
          git config --global user.email "streakbot@users.noreply.github.com"

      - name: Run and Commit
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          # Create/modify a file
          echo "Last run: $(date)" >> streak.log
          
          # Commit changes
          git add .
          if git diff --cached --quiet; then
            echo "No changes detected"
          else
            git commit -m "🤖 Auto-update: $(date +'%Y-%m-%d %H:%M')"
            git push
            echo "Changes pushed successfully"
          fi