name: Run StreakBot Daily

on:
  workflow_dispatch:       # <--- Manual trigger from GitHub UI
  push:                    # <--- Trigger on any push to main
    branches:
      - main
  schedule:                # <--- Scheduled run every minute
    - cron: '*/1 * * * *'

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run StreakBot
        run: python streakbot.py
